- name: Install nginx
  hosts: mongodb
  become: yes
  tasks: 
  - name: Install nginx
    ansible.builtin.yum:
     name: nginx
     state: installed
  - name: Start nginx
    ansible.builtin.service:
     name: nginx
     state: started

   