- name: Print variables from file
  hosts: localhost
  vars_files:
    - variables.yaml
  tasks:
    - name: Printing variables
      ansible.builtin.debug:
        msg: I am learning {{Name}}, Duration is {{Duration}}, Quote is {{Quotes}}