- name: Install apps
  hosts: mongodb
  become: yes
  tasks:
  - name: Install app
    ansible.builtin.yum:
      name: "{{item}}"
      state: installed
    loop:
    - nginx
    - postfix
    - mailx